# image: python:3.10.8-buster
image: mk1990hpi/simba_ml_env:latest

stages:
  - test
  - build

before_script:
  - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

lint:
  stage: test
  script:
    - sourcery login --token $SOURCERY_TOKEN
    - make lint
    - make tests-lint

pytest:
  stage: test
  script:
    - make test
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

documentation:
  stage: build
  script:
    - make doctest
    - make documentation
    - mkdir public
    - mv docs/build/html public
  artifacts:
    paths:
      - public

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - dist
  only:
    - main
